version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8081
    environment:
      FLASK_ENV: development
    depends_on:
      mariadb:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
      
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: lulu1234
      MARIADB_DATABASE: spacelegends
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      interval: 30s
      retries: 3
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      timeout: 30s

volumes:
  dbdata: